name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      #  working-directory: react-app
      - run: npm run format:check
        #working-directory: react-app
      - run: npm test -- --coverage
       # working-directory: react-app
        env:
          CI: true
      - name: Build Project
        run: npm run build